---
- name: (Debian/Ubuntu)
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - gpg-agent
    update_cache: true
    state: latest 
  when: ansible_facts['os_family'] == 'Debian'

- name: (CentOS/RHEL)
  yum:
    name: 
      - ca-certificates
      - epel-release
    update_cache: true
    state: latest 
  when: ansible_facts['os_family'] == 'RedHat'

