- name: "Install nginx Debian/ubuntu"
  apt:
    name: nginx {{ nginx_version }}
    state: present
    update_cache: true

- name: Allow all access to tcp port 80/443
  community.general.ufw:
    rule: allow
    port:
      - 80
      - 443
    proto: tcp
