---
- name: download from repo
  get_url:
    url: https://dev.mysql.com/get/mysql80-community-release-el9-5.noarch.rpm
    dest: /opt/mysql

- name: Install package
  yum:
    name: /opt/mysql/mysql80-community-release-el9-5.noarch.rpm
    state: present

- name: install MySQL
  yum: 
    name: mysql-server
    state: present

- name: run MySQL
  service: 
    name: mysqld
    state: started
    enabled: yes


