---
# tasks file for mysql
- name: "Install mysql Debian-based"
  include_tasks: "./install-debian.yml"
  when: ansible_facts['os_family'] == 'Debian'

- name: "Install mysql RHEL-based"
  include_tasks: "./install-rhel.yml"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Enable service in systemd
  include_tasks: "./systemd.yml"
  when:
    - ansible_facts['service_mgr'] == 'systemd'

- name: Start mysql, if not started
  service:
    name: mysqld
    state: started
